image: python:3.11  # 使用合适的Python版本

stages:
  - test

# 安装 pytest 的任务
install_pytest:
  stage: test
  script:
    - which python  # 检查 Python 是否在 PATH 中
    - which pip     # 检查 pip 是否在 PATH 中
    - python --version
    - python -m ensurepip --upgrade  # 确保 pip 已经安装并升级
    - python -m pip install --upgrade pip  # 升级 pip
    - python -m pip install pytest  # 安装 pytest
  artifacts:
    paths:
      - .pytest_cache/  # 包含pytest的缓存文件，有助于加速后续的测试运行


# 定义并行测试任务
pytest_parallel:
  stage: test
  dependencies:
    - install_pytest  # 确保 pytest 被正确安装
  parallel:
    matrix:
      - TEST_FILE: ["test_lab1.py", "test_lab3.py", "test_lab4.py"]
  script:
    - python -m pytest $TEST_FILE  # 使用 python -m pytest 运行测试
